# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fc40a063ebb8b22eb6d71e45cd8090ac3b5a090811c7d44fe29291f8c5ee4ae740d6bdc28fdd9594315edc71d85b92c5bb3effb5b80d9b04b234605df92d3edb

test:
  secret_key_base: 4e6992128f4873f1d8e9f299be1cc5bdefb4e9bc9dd98ae5bb3d081764f2bb6af9f274846dadbeed25ace51d0318678075436601e328dbf801cef5d05680dacc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
